# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 31, 202, 133))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_titel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titel.setFont(font)
        self.label_titel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titel.setObjectName("label_titel")
        self.verticalLayout.addWidget(self.label_titel)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_dezimal = QtWidgets.QLabel(self.widget)
        self.label_dezimal.setObjectName("label_dezimal")
        self.gridLayout.addWidget(self.label_dezimal, 0, 0, 1, 1)
        self.lineEdit_dezimal = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_dezimal.setObjectName("lineEdit_dezimal")
        self.gridLayout.addWidget(self.lineEdit_dezimal, 0, 1, 1, 2)
        self.label_dual = QtWidgets.QLabel(self.widget)
        self.label_dual.setObjectName("label_dual")
        self.gridLayout.addWidget(self.label_dual, 1, 0, 1, 1)
        self.lineEdit_dual = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_dual.setObjectName("lineEdit_dual")
        self.gridLayout.addWidget(self.lineEdit_dual, 1, 1, 1, 2)
        self.btn_dez_zu_dual = QtWidgets.QPushButton(self.widget)
        self.btn_dez_zu_dual.setObjectName("btn_dez_zu_dual")
        self.gridLayout.addWidget(self.btn_dez_zu_dual, 2, 0, 1, 2)
        self.btn_dual_zu_dez = QtWidgets.QPushButton(self.widget)
        self.btn_dual_zu_dez.setObjectName("btn_dual_zu_dez")
        self.gridLayout.addWidget(self.btn_dual_zu_dez, 2, 2, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.widget)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 3, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Zahlensystem-Konverter"))
        self.label_titel.setText(_translate("MainWindow", "Zahlensystem-Konverter"))
        self.label_dezimal.setText(_translate("MainWindow", "Dezimalzahl:"))
        self.label_dual.setText(_translate("MainWindow", "Dualzahl:"))
        self.btn_dez_zu_dual.setText(_translate("MainWindow", "Dez. --> Dual"))
        self.btn_dual_zu_dez.setText(_translate("MainWindow", "Dual --> Dez."))
        self.btn_clear.setText(_translate("MainWindow", "Eingaben löschen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
